# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20170922_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='Author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abc', to='first.BookInfo'),
        ),
        migrations.AlterField(
            model_name='author',
            name='Author_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ab', to='first.BookInfo'),
        ),
    ]
