# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_auto_20170922_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='Author_name',
        ),
        migrations.AddField(
            model_name='author',
            name='Author_name',
            field=models.ManyToManyField(related_name='ab', to='first.BookInfo'),
        ),
    ]
