# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_auto_20170922_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
                ('dept_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelfno', models.IntegerField()),
                ('book_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Department')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='Author_book',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lib',
            name='books_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Author'),
        ),
        migrations.AddField(
            model_name='lib',
            name='student_name',
            field=models.ManyToManyField(to='first.StudentInfo'),
        ),
    ]
