# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_auto_20170922_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='Author_id',
        ),
        migrations.RemoveField(
            model_name='lib',
            name='books_author',
        ),
        migrations.AddField(
            model_name='lib',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first.BookInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='Author_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abc', to='first.BookInfo'),
        ),
        migrations.RemoveField(
            model_name='lib',
            name='student_name',
        ),
        migrations.AddField(
            model_name='lib',
            name='student_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='first.StudentInfo'),
            preserve_default=False,
        ),
    ]
