# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_auto_20170922_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='Author_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jyoti', to='first.BookInfo'),
        ),
        migrations.RemoveField(
            model_name='author',
            name='Author_name',
        ),
        migrations.AddField(
            model_name='author',
            name='Author_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rinku', to='first.BookInfo'),
        ),
    ]
