# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_auto_20170922_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doct_name', models.CharField(max_length=60)),
                ('doct_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosp_name', models.CharField(max_length=60)),
                ('hosp_addr', models.CharField(max_length=50)),
                ('hosp_wards', models.CharField(max_length=60)),
                ('hosp_doct', models.ManyToManyField(to='first.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='doct_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Patient'),
        ),
    ]
