# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0010_auto_20170923_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='hosp_doct',
            new_name='hospdoct',
        ),
    ]
