# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 10:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_auto_20170923_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='date',
            field=models.DateField(default=datetime.date(2017, 9, 23)),
            preserve_default=False,
        ),
    ]
