# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0012_hospital_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='p_email',
            field=models.EmailField(default='email@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
